name: mi_app
description: Una app Flutter para gestión de tareas y productividad
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ICONOS Y MATERIALES
  cupertino_icons: ^1.0.8

  # 🧠 Persistencia local y utilidades
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

  # 👇 NUEVAS para backup/restore
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  share_plus: ^10.0.2

  # notificaciones
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
